using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ACBr.Net.ECF
{
    internal class ACBrECFDaruma
    {
        #region Fields

        #region MsgErros

        readonly Dictionary<int, string> Erros = new Dictionary<int, string>()
        {
            { 1 , "ECF com falha mecânica"},
            { 2 , "MF não conectada"},
            { 3 , "MFD não conectada"},
            { 4 , "MFD esgotada"},
            { 5 , "Erro na comunicação com a MF"},
            { 6 , "Erro na comunicação com a MFD"},
            { 7 , "MF não inicializada"},
            { 8 , "MFD não inicializada"},
            { 9 , "MFD já inicializada"},
            { 10 , "MFD foi substituída"},
            { 11 , "MFD já cadastrada"},
            { 12 , "Erro na inicialização da MFD"},
            { 13 , "Faltam parâmetros de inicialização na MF"},
            { 14 , "Comando não suportado"},
            { 15 , "Superaquecimento da cabeça de impressão"},
            { 16 , "Perda de dados da MT"},
            { 17 , "Operação habilitada apenas em MIT"},
            { 18 , "Operação habilitada apenas em modo fiscal"},
            { 19 , "Data inexistente"},
            { 20 , "Data inferior ao do último documento"},
            { 21 , "Intervalo inconsistente"},
            { 22 , "Não existem dados"},
            { 23 , "Clichê de formato inválido"},
            { 24 , "Erro no verificador da comunicação"},
            { 25 , "Senha incorreta"},
            { 26 , "Número de decimais para quantidade inválido"},
            { 27 , "Número de decimais para valor unitário inválido"},
            { 28 , "Tipo de impressão de FD inválido"},
            { 29 , "Caracter não estampável"},
            { 30 , "Caracter não estampável ou em branco"},
            { 31 , "Caracteres não podem ser repetidos"},
            { 32 , "Limite de itens atingido"},
            { 33 , "Todos os totalizadores fiscais já estão programados"},
            { 34 , "Totalizador fiscal já programado"},
            { 35 , "Todos os totalizadores não fiscais já estão programados"},
            { 36 , "Totalizador não fiscal já programado"},
            { 37 , "Todos os relatórios gerenciais já estão programados"},
            { 38 , "Relatório gerencial já programado"},
            { 39 , "Meio de pagamento já programado"},
            { 40 , "Índice inválido"},
            { 41 , "Índice do meio de pagamento inválido"},
            { 42 , "Erro gravando número de decimais na MF"},
            { 43 , "Erro gravando moeda na MF"},
            { 44 , "Erro gravando símbolos de decodificação do GT na MF"},
            { 45 , "Erro gravando número de fabricação da MFD na MF"},
            { 46 , "Erro gravando usuário na MF"},
            { 47 , "Erro gravando GT do usuário anterior na MF"},
            { 48 , "Erro gravando registro de marcação na MF"},
            { 49 , "Erro gravando CRO na MF"},
            { 50 , "Erro gravando impressão de FD na MF"},
            { 51 , "Campo em branco ou zero não permitido"},
            { 52 , "Campo reservado a gravação da moeda na MF esgotado"},
            { 53 , "Campo reservado a gravação da tabela de GT na MF esgo"},
            { 54 , "Campo reservado a gravação do NS da MFD na MF esgo"},
            { 55 , "Campo reservado a gravação de usuário na MF esgotado"},
            { 56 , "CNPJ inválido"},
            { 57 , "CRZ e CRO em zero"},
            { 58 , "Intervalo invertido"},
            { 59 , "Utilize apenas 0 ou 1"},
            { 60 , "Configuração permitida apenas imediatamente a RZ"},
            { 61 , "Símbolo gráfico inválido"},
            { 62 , "Falta pelo menos 1 campo no nome da moeda para chequ"},
            { 63 , "Código supera o valor 255"},
            { 64 , "Utilize valores entre 25 e 80"},
            { 65 , "Utilize valores entre 1 e 15"},
            { 66 , "Utilize valores entre 0 e 7250"},
            { 67 , "Data informada não coincide com a data do ECF"},
            { 68 , "Deve ajustar o relógio ( utilize o comando [FS] M <200> )"},
            { 69 , "Erro ao ajustar o relógio"},
            { 70 , "Capacidade da MF esgotada"},
            { 71 , "Versão do SB gravado na MF incorreta"},
            { 72 , "Fim do papel"},
            { 73 , "Nenhum usuário programado"},
            { 74 , "Utilize apenas dígitos numéricos"},
            { 75 , "Campo não pode estar em zero"},
            { 76 , "Campo não pode estar em branco"},
            { 77 , "Valor da operação não pode ser zero"},
            { 78 , "CF aberto"},
            { 79 , "CNF aberto"},
            { 80 , "CCD aberto"},
            { 81 , "RG aberto"},
            { 82 , "CF não aberto"},
            { 83 , "CNF não aberto"},
            { 84 , "CCD não aberto"},
            { 85 , "RG não aberto"},
            { 86 , "CCD ou RG não aberto"},
            { 87 , "Documento já totalizado"},
            { 88 , "RZ do movimento anterior pendente"},
            { 89 , "Já emitiu RZ de hoje"},
            { 90 , "Totalizador sem alíquota programada"},
            { 91 , "Campo de código ausente"},
            { 92 , "Campo de descrição ausente"},
            { 93 , "VU ou quantidade em zero"},
            { 94 , "Item ainda não vendido"},
            { 95 , "Desconto ou acréscimo não pode ser zero"},
            { 96 , "Item já possui desconto ou acréscimo"},
            { 97 , "Ítem cancelado"},
            { 98 , "Operação inibida por configuração"},
            { 99 , "Opção não suportada"},
            { 100 , "Desconto ou acréscimo supera valor bruto"},
            { 101 , "Desconto ou acréscimo final de valor zero"},
            { 102 , "Valor bruto zero"},
            { 103 , "Overflow no valor do item"},
            { 104 , "Overflou no valor do desconto ou acréscimo"},
            { 105 , "Overflow na capacidade do documento"},
            { 106 , "Overflow na capacidade do totalizador"},
            { 107 , "Item não possui desconto"},
            { 108 , "Item já possui desconto"},
            { 109 , "Quantidade possui mais de 2 decimais"},
            { 110 , "Valor unitário possui mais de 2 decimais"},
            { 111 , "Quantidade a cancelar deve ser inferior a total"},
            { 112 , "Campo de descrição deste item não mais presente na MT"},
            { 113 , "Subtotal não possui desconto ou acréscimo"},
            { 114 , "Não em fase de totalização"},
            { 115 , "Não em fase de venda ou totalização"},
            { 116 , "Mais de 1 desconto ou acréscimo não permitido"},
            { 117 , "Valor do desconto ou acréscimo supera subtotal"},
            { 118 , "Meio de pagamento não programado"},
            { 119 , "Não em fase de pagamento ou totalização"},
            { 120 , "Não em fase de finalização de documento"},
            { 121 , "Já emitiu mais CCDs que poderia estornar"},
            { 122 , "Último documento não é cancelável"},
            { 123 , "Estorne CCDs"},
            { 124 , "Último documento não foi CF"},
            { 125 , "Último documento não foi CNF"},
            { 126 , "Não pode cancelar"},
            { 127 , "Pagamento não mais na MT"},
            { 128 , "Já emitiu CCD deste pagamento"},
            { 129 , "RG não programado"},
            { 130 , "CNF não programado"},
            { 131 , "Cópia não disponível"},
            { 132 , "Já emitiu segunda via"},
            { 133 , "Já emitiu reimpressão"},
            { 134 , "Informações sobre o pagamento não disponíveis"},
            { 135 , "Já emitiu todas as parcelas"},
            { 136 , "Parcelamento somente na sequência"},
            { 137 , "CCD não encontrado"},
            { 138 , "Não pode utilizar SANGRIA ou SUPRIMENTO"},
            { 139 , "Pagamento não admite CCD"},
            { 140 , "Relógio inoperante"},
            { 141 , "Usuário sem CNPJ"},
            { 142 , "Usuário sem IM"},
            { 143 , "Não se passou 1 hora após o fechamento do último documen"},
            { 144 , "ECF OFF LINE"},
            { 145 , "Documento em emissão"},
            { 146 , "COO não coincide"},
            { 147 , "Erro na autenticação"},
            { 148 , "Erro na impressão de cheque"},
            { 149 , "Data não pertence ao século XXI"},
            { 150 , "Usuário já programado"},
            { 151 , "Descrição do pagamento já utilizada"},
            { 152 , "Descrição do totalizador já utilizada"},
            { 153 , "Descrição do RG já utilizada"},
            { 154 , "Já tem desconto após acréscimo ( ou vice versa )"},
            { 155 , "Já programou 15 totalizadores para ICMS"},
            { 156 , "Já programou 15 totalizadores para ISS"},
            { 157 , "MFD com problemas"},
            { 158 , "Razão social excede 48 caracteres"},
            { 159 , "Nome fantasia excede 48 caracteres"},
            { 160 , "Endereço excede 120 caracteres"},
            { 161 , "Identificação do programa aplicativo ausente"},
            { 162 , "Valor de desconto supera valor acumulado em totalizador"},
            { 163 , "Número de parcelas no pagamento não pode exceder 24"},
            { 164 , "MFD não cadastrada"},
            { 165 , "Excedeu limite de impressão de FD ( capacidade na MF esgotada )"},
            { 166 , "Efetivado é igual ao estornado"},
            { 167 , "Símbolo da moeda já programado"},
            { 168 , "UF inválida"},
            { 169 , "UF já programada"},
            { 170 , "Erro gravando UF"},
            { 171 , "Leitor CMC-7 não instalado"},
            { 172 , "Erro de leitura do código CMC-7"},
            { 173 , "Autenticação não permitida"},
            { 174 , "Operação somente com mecanismo matricial de impacto"},
            { 175 , "Coordenadas de cheque inválidas"},
            { 176 , "Impressão do verso do cheque somente após a impressão da frente"},
            { 177 , "Indice do bitmap inválido"},
            { 178 , "Bitmap de tamanho inválido"},
            { 179 , "Última RZ a mais de 30 dias. Comando de RZ deve informar data correta"},
            { 180 , "Erro não documentado"},
            { 181 , "Erro não documentado"},
            { 182 , "Erro não documentado"},
            { 183 , "Erro não documentado"},
            { 184 , "Parâmetro só pode ser \"A\" ou \"T\""},
            { 185 , "Erro não documentado"},
            { 186 , "Erro não documentado"},
            { 187 , "Erro não documentado"},
            { 188 , "Erro não documentado"},
            { 189 , "Erro não documentado"},
            { 190 , "Erro não documentado"},
            { 191 , "Erro não documentado"},
            { 192 , "Erro não documentado"},
            { 193 , "Erro não documentado"},
            { 194 , "Erro não documentado"},
            { 195 , "Erro não documentado"},
            { 196 , "Erro não documentado"},
            { 197 , "Erro não documentado"},
            { 198 , "Erro não documentado"},
            { 199 , "Erro não documentado"},
            { 200 , "Erro não documentado"},
            { 201 , "Erro não documentado"},
            { 202 , "Erro não documentado"},
            { 203 , "Erro não documentado"},
            { 204 , "Erro não documentado"},
            { 205 , "Erro não documentado"},
            { 206 , "Erro não documentado"},
            { 207 , "Erro não documentado"},
            { 208 , "Erro não documentado"},
            { 209 , "Erro não documentado"},
            { 210 , "Erro não documentado"},
            { 211 , "Erro não documentado"},
            { 212 , "Erro não documentado"},
            { 213 , "Erro não documentado"},
            { 214 , "Erro não documentado"},
            { 215 , "Erro não documentado"},
            { 216 , "Erro não documentado"},
            { 217 , "Erro não documentado"},
            { 218 , "Erro não documentado"},
            { 219 , "Erro não documentado"},
            { 220 , "Erro não documentado"},
            { 221 , "Erro não documentado"},
            { 222 , "Erro não documentado"},
            { 223 , "Erro não documentado"},
            { 224 , "Erro não documentado"},
            { 225 , "Erro não documentado"},
            { 226 , "Erro não documentado"},
            { 227 , "Erro não documentado"},
            { 228 , "Erro não documentado"},
            { 229 , "Erro não documentado"},
            { 230 , "Erro não documentado"},
            { 231 , "Erro não documentado"},
            { 232 , "Erro não documentado"},
            { 233 , "Erro não documentado"},
            { 234 , "Erro não documentado"},
            { 235 , "Erro não documentado"},
            { 236 , "Erro não documentado"},
            { 237 , "Erro não documentado"},
            { 238 , "Erro não documentado"},
            { 239 , "Erro não documentado"},
            { 240 , "Erro não documentado"},
            { 241 , "Erro não documentado"},
            { 242 , "Erro não documentado"},
            { 243 , "Erro não documentado"},
            { 244 , "Erro não documentado"},
            { 245 , "Erro não documentado"},
            { 246 , "Erro não documentado"},
            { 247 , "Erro não documentado"},
            { 248 , "Erro não documentado"},
            { 249 , "Erro não documentado"},
            { 250 , "Erro não documentado"},
            { 251 , "Erro não documentado"},
            { 252 , "Erro não documentado"},
            { 253 , "Erro não documentado"},
            { 254 , "Erro não documentado"},
            { 255 , "Erro não documentado"},
            { 256 , "Erro não documentado"},
            { 257 , "Erro não documentado"},
            { 258 , "Erro não documentado"},
            { 259 , "Erro não documentado"},
            { 260 , "Erro não documentado"},
            { 261 , "Erro não documentado"},
            { 262 , "Erro não documentado"},
            { 263 , "Erro não documentado"},
            { 264 , "Erro não documentado"},
            { 265 , "Erro não documentado"},
            { 266 , "Erro não documentado"},
            { 267 , "Erro não documentado"},
            { 268 , "Erro não documentado"},
            { 269 , "Erro não documentado"},
            { 270 , "Erro não documentado"},
            { 271 , "Erro não documentado"},
            { 272 , "Erro não documentado"},
            { 273 , "Erro não documentado"},
            { 274 , "Erro não documentado"},
            { 275 , "Erro não documentado"},
            { 276 , "Erro não documentado"},
            { 277 , "Erro não documentado"},
            { 278 , "Erro não documentado"},
            { 279 , "Erro não documentado"},
            { 280 , "Erro não documentado"},
            { 281 , "Erro não documentado"},
            { 282 , "Erro não documentado"},
            { 283 , "Erro não documentado"},
            { 284 , "Erro não documentado"},
            { 285 , "Erro não documentado"},
            { 286 , "Erro não documentado"},
            { 287 , "Erro não documentado"},
            { 288 , "Erro não documentado"},
            { 289 , "Erro não documentado"},
            { 290 , "Erro não documentado"},
            { 291 , "Erro não documentado"},
            { 292 , "Erro não documentado"},
            { 293 , "Erro não documentado"},
            { 294 , "Erro não documentado"},
            { 295 , "Erro não documentado"},
            { 296 , "Erro não documentado"},
            { 297 , "Erro não documentado"},
            { 298 , "Erro não documentado"},
            { 299 , "Erro não documentado"},
            { 300 , "Erro não documentado"},
            { 301 , "CFBP Inibido"},
            { 302 , "Modalidade de Transporte inválida"},
            { 303 , "Categoria de Transporte inválida"},
            { 304 , "UF incompatível"},
            { 305 , "Comando disponível apenas em CF genérico"}
        };

        #endregion MsgErros

        #endregion Fields
    }
}
